[[repos]]
repo = "local"

[[repos.hooks]]
id = "format"
name = "format rust files"
entry = "cargo fmt"
language = "system"
pass_filenames = false
always_run = true
stages = ["pre-commit"]

[[repos]]
repo = "https://github.com/compilerla/conventional-pre-commit"
rev = "v3.4.0"

[[repos.hooks]]
id = "conventional-pre-commit"
stages = ["commit-msg"]
args = ["feat", "fix", "chore", "refactor", "style", "docs", "test", "perf", "build", "ci", "revert"]
